mysql:
  dataBase: autosign
  userName: root
  passWord: 123456
  port: 8086
  driverName: mysql
  host: url
  log-level: debug
  max-idle-conns: 10
  max-open-conns: 100
  conn-max-life-time: 5
#  🛠️🔧⛏️🗝️⚙️🧬💡
logger:
  level: info
  prefix: '[🛠️]'
  director: log
  showLine: true
  logInConsole: true
mail:
  host: you-host
  port: you-port
  user: you-user
  password: you-password
  ssl: true
  local-home:         #可选