name: BronyaBot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # 手动触发的情况
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...




        # 打包二进制文件
      - name: Build Binary
        run: |
          mkdir -p ./bin
          GOOS=linux GOARCH=amd64 go build -o ./bin/BronyaBot-linux-amd64 .
          GOOS=windows GOARCH=amd64 go build -o ./bin/BronyaBot-windows-amd64.exe .
          GOOS=darwin GOARCH=amd64 go build -o ./bin/BronyaBot-darwin-amd64 .


      - name: List files in bin directory
        run: ls -l ./bin

      - name: Package Source Code
        run: |
          echo "Packaging source code..."
          tar -czvf ./bin/BronyaBot-source.tar.gz .
      

      # 创建 Git 标签
      - name: Create Git Tag
        run: |
          TAG_NAME=v$(date +'%Y%m%d%H%M%S')  # 使用当前时间戳创建标签
          git tag $TAG_NAME
          git push origin $TAG_NAME

      # 发布二进制文件和源代码到 GitHub Releases
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./bin/BronyaBot-linux-amd64
            ./bin/BronyaBot-windows-amd64.exe
            ./bin/BronyaBot-darwin-amd64
            ./bin/BronyaBot-source.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
